stages:
    - build
    - test
    - deploy 

compile:
  stage: build
  image: docker:20
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo "Starting build phase"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:world-in-pictures" .
    - docker push "$CI_REGISTRY_IMAGE:world-in-pictures"

test:
  stage: test
  needs:
    - job: compile
  image: "maven:3.8.4-openjdk-11"
  services:
    - docker:dind
  tags:
    - docker
  script:
    - "mvn test"

publish:
  stage: deploy
  image: docker:20
  services:
    - docker:dind
  tags:
    - docker
  needs:
    - job: compile
      artifacts: true
    - job: test
      artifacts: true
  before_script:
    - echo "Starting deployment phase"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:world-in-pictures"
    - docker push "$CI_REGISTRY_IMAGE:world-in-pictures"
