varables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
stages:
    - build
    - test
    - deploy 

cache:
  path:
    - .m2/repository
    - target

# Compile sources and test-sources
compile:
  stage: build
  tags:
    - docker
  script:
    - "mvn compile"



test:
  stage: test
  needs:
    - job: compile
  tags:
    - docker
  script:
    - "mvn test"
