stages:
    - build
    - test
    - release
    - deploy 

compile:
  stage: build
  image: docker:20
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo "Starting build phase"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:world-in-pictures" .
    - docker push "$CI_REGISTRY_IMAGE:world-in-pictures"

test:
  stage: test
  needs:
    - job: compile
  image: "maven:3.8.4-openjdk-11"
  services:
    - docker:dind
  tags:
    - docker
  script:
    - "mvn test"

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - Tsveti