stages:
    - build
    - test
    - deploy 

compile:
  stage: build
  image: "maven:3.8.4-openjdk-11"
  tags:
    - docker
  script:
    - "mvn compile"

test:
  stage: test
  needs:
    - job: compile
  image: "maven:3.8.4-openjdk-11"
  tags:
    - docker
  script:
    - "mvn test"
