stages:
    - build
    - test
    - deploy 

compile:
  stage: build
  tags:
    - docker
  script:
    - "mvn compile"

test:
  stage: test
  needs:
    - job: compile
  tags:
    - docker
  script:
    - "mvn test"
