name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change this to your desired Java version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Test with Maven
      run: mvn -B test --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Deploy to Artifactory
      run: mvn -B deploy --file pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
